/*
 * ASR documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloud_asr

type AdvancedRecognitionRequestDto struct {

	// Recognize with package
	PackageId string `json:"package_id,omitempty"`

	// Specific channels to process
	Channels []int32 `json:"channels,omitempty"`

	// Binary audio file as Base64 string
	Data string `json:"data"`
}
