/*
 * ASR documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloud_asr

type PackageDto struct {

	// Package ID
	PackageId string `json:"package_id"`

	// Package name
	Name string `json:"name"`

	// Package language
	Language string `json:"language"`

	// Required sample rate of data
	SampleRate int32 `json:"sample_rate"`

	// Is package loaded to the cache
	Loaded bool `json:"loaded"`
}
