/*
 * ASR documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloud_asr

type WordDto struct {

	// Recognized word
	Word string `json:"word"`

	// Identified speaker id
	Speaker int32 `json:"speaker,omitempty"`

	// Recognition confidence (0 - 100.00)
	Score string `json:"score"`

	// Time stamp on which this word was found
	Begin string `json:"begin,omitempty"`

	// Word duration
	Length string `json:"length,omitempty"`

	// Word stop sign
	StopSign string `json:"stop_sign,omitempty"`
}
