/*
 * ASR documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.dev
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloud_asr

type WordDto struct {

	// Recognized word
	Word string `json:"word"`

	// Recognition confidence (0 - 100.00)
	Score string `json:"score"`

	// Time stamp on which this word was found
	Begin string `json:"begin,omitempty"`

	// Word duration
	Length string `json:"length,omitempty"`
}
