/*
 * TTS documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloud_tts

type CloseTransactionResponse struct {

	TransactionId string `json:"transaction_id,omitempty"`

	SynthesizeTextSize int64 `json:"synthesize_text_size,omitempty"`
}
