/*
 * TTS documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloud_tts

type Credentials struct {

	// Username
	Username string `json:"username"`

	// Password
	Password string `json:"password"`

	// Domain ID
	DomainId string `json:"domain_id"`
}
