/*
 * TTS documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.1.73
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloud_tts

type ExceptionModel struct {

	// Reason of exception
	Reason string `json:"reason"`

	// Message of exception
	Message string `json:"message"`
}
