/*
 * TTS documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloud_tts

type SynthesizeResponse struct {

	// Result speech in data with base64 coding
	Data string `json:"data"`
}
