/*
 * TTS documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloud_tts

type SynthesizeLanguage struct {

	// Language id
	Id string `json:"id"`

	// Language name
	Name string `json:"name"`
}
