/*
 * TTS documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.1.73
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloud_tts

type SynthesizeVoiceType struct {

	// Voice id
	Id string `json:"id"`

	// Name of voice
	Name string `json:"name"`

	// Gender of voice
	Gender string `json:"gender"`
}
