/*
 * Diarization documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.1.73
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloud_diarization

type Audio struct {

	// Audio in base64 for diarization
	Data string `json:"data"`

	// Mime type of audio. Possible value: audio/alaw, audio/mulaw, audio/s16be, audio/wav
	Mime string `json:"mime"`
}
