/*
 * SessionService documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloud_diarization

// Auth information provided after authentication
type AuthResponseDto struct {

	// Session identifier to be provided in header on all REST API results
	SessionId string `json:"session_id,omitempty"`
}
