/*
 * Diarization documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.1.73
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloud_diarization

type DiarizationResponse struct {

	// Result speech in data with base64 coding
	Data *DiarizationResult `json:"data"`
}
