/*
 * SessionService documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloud_diarization

type DomainDto struct {

	Id int64 `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	IsDeleted bool `json:"is_deleted,omitempty"`
}
