/*
 * Diarization documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 3.1.73
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloud_diarization

type Speaker struct {

	Number int32 `json:"number,omitempty"`

	Segments []Segment `json:"segments,omitempty"`
}
