/*
 * Diarization documentation
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.1
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package cloud_diarization

type SpeakerDto struct {

	Number int32 `json:"number,omitempty"`

	Segments []SegmentDto `json:"segments,omitempty"`
}
